### ISSUE TITLE
Make DNA hash optional again

### ISSUE THREAD

**Issue by nmrshll** [holochain/holochain-rust#1600]
Since v0.0.23, in the `holochain` conductor's config file, in `[[dnas]]`, the value `hash` is required again.

For developers, this seems to mean that we'll have to update the hash for every change in the zome code (manually or in automated fashion).

Is it possible to make that value optional again ? Or what is the justification behind that change ?
Thanks in advance

**Comment by tjdforb** [comment]
See https://github.com/holochain/holochain-rust/pull/1335

**Comment by lucksus** [comment]
I was about to respond that the way to run DNAs when developing is `hc run`. But then I first checked and found that we missed to update `hc` to actually set the right hash. I've just pushed a [PR to fix that](https://github.com/holochain/holochain-rust/pull/1603) which unfortunately missed the code freeze for version 0.0.25 this morning and will go into 0.0.26 next week.

For context:
This DNA hash check was introduced to help exactly with your use-case: running the conductor during development. There was a pitfall that had cost both the Holo as well as the Holochain core team several hours of debugging. If you run a production conductor (=`holochain`) for the first time it will read your DNA file and create an instance from that. That instance will initialize the source chain with that DNA as its first entry. The source chain is stored in the CAS (the storage that you configure in the conductor config with the instance). If you would now change your DNA code, recompile the DNA and replace the DNA file and then restart the conductor, you would still run the old DNA version since that is what is stored in the source chain. You would actually have to clean the storage to have `holochain` recreate the chain from the new file.

Making the hash mandatory and thus forcing the developer to explicitly say which DNA to run makes it possible that the conductor checks the version in the storage against that hash as well as the file against that hash. And complain if you have changed the file without changing the other two.

You should use `hc run`. If you want to use `holochain` for development you can easily get the hash of your DNA file with `hc hash -p <DNA file path>`.

**Comment by pythagorean** [comment]
> You should use `hc run`. If you want to use `holochain` for development you can easily get the hash of your DNA file with `hc hash -p <DNA file path>`.

Am I understanding that #1594 won't be fixed until 0.0.26?

**Comment by nmrshll** [comment]
@lucksus Thanks for the insight on how the CAS works and is initialized, it's useful to have a mental picture of what happens there. I had switched to in-memory storage to avoid any storage conflict (different DNAs trying to store in the same folder). For now I'm using `hc hash` and piping into a `hcconfig.toml` template (so putting the a fresh hash every time I run the app). Since I use in-memory storage there shouldn't be any conflicts, right ?

About `hc run`, it doesn't have all the features of the production conductor, does it ? I'm thinking of log filtering, UI bundles / interfaces, http interfaces, multi-agent, multi-instance ?

Thanks

**Comment by lucksus** [comment]
@pythagorean, There is a fix up in https://github.com/holochain/holochain-rust/pull/1603 which you could checkout and build and install `hc` by running
```
hc-cli-install
```
from a nix-shell.

And yes, since 0.0.25 is frozen already the earliest this can be included in a release is 0.0.26.

**Comment by lucksus** [comment]
@nmrshll, right, `hc` does not make all features of the conductor available. From what you mention, you can have it open an http instead of a websocket interface with `-i http`:
```
[nix-shell:~/code/holochain-rust]$ hc run --help
hc-run 0.0.24-alpha2
Holochain Core Dev Team <devcore@holochain.org>
Starts a development conductor with a websocket or http interface

USAGE:
    hc run [FLAGS] [OPTIONS]

FLAGS:
    -h, --help         Prints help information
        --logging      Produce logging output
        --networked    Use real networking
    -b, --package      Automatically package project before running
        --persist      Save generated data to file system
    -V, --version      Prints version information

OPTIONS:
    -d, --dna <dna_path>           Absolute path to the .dna.json file to run. [default: ./dist/<dna-name>.dna.json]
    -i, --interface <interface>    Specify interface type to use: websocket/http [default: websocket]
    -p, --port <port>              The port to run the websocket server at [default: 8888]
```
`hc run` executes the same conductor code but creates an internal config without writing/reading it to/from file. I would rather add more config options to `hc run` than making the hash optional again. Would you agree?

**Comment by nmrshll** [comment]
@lucksus sounds good ! I only switched to `holochain` to get its features, and it makes sense to add these features to `hc` than to degrade `holochain` to fit a development workflow. `hc` is the one that's meant for development after all

**Comment by nmrshll** [comment]
> @pythagorean, There is a fix up in #1603 which you could checkout and build and install `hc` by running
> 
> ```
> hc-cli-install
> ```
> 
> from a nix-shell.
> 
> And yes, since 0.0.25 is frozen already the earliest this can be included in a release is 0.0.26.

For those who haven't jumped on the nix bandwagon yet, all of holochain can be installed easily with cargo (bonus: it lets you choose the exact version you want for every dependency (which is useful e.g. if you want to lock the deps' version in each project)):

```bash
rustup --version || curl https://sh.rustup.rs -sSf | sh -s -- -y
rustup show |grep wasm32-unknown-unknown || rustup target add wasm32-unknown-unknown
rustup default | grep nightly-2019-01-24 || rustup default nightly-2019-01-24
holochain --version | grep 0.0.23-alpha1 || cargo install holochain --force --git https://github.com/holochain/holochain-rust.git --tag v0.0.23-alpha1
hc --version | grep 0.0.23-alpha1 || cargo install hc --force --git https://github.com/holochain/holochain-rust.git --tag v0.0.23-alpha1
```

**Comment by pospi** [comment]
> I would rather add more config options to `hc run` than making the hash optional again. Would you agree?

I wouldn't really, unless you are planning on upgrading `hc` to support a conductor configuration. You're limiting development to be a "one DNA at a time" thing; there are those of us who need to run multiple DNAs together, with bridging, in our development environment.

**Comment by lucksus** [comment]
> I wouldn't really, unless you are planning on upgrading hc to support a conductor configuration. You're limiting development to be a "one DNA at a time" thing; there are those of us who need to run multiple DNAs together, with bridging, in our development environment.

I regard the use-case of having hc quickly run a hApp of one of those that will benefit from the recently introduced [hApp bundles](https://github.com/holochain/holoscape/tree/master/example-bundles). IMHO hc should not stay limited to "one DNA at a time". Without bundles it was unclear how `hc run` can easily put together a conductor config (since that's what it is doing under the hood) without needing a full config as input (since writing that means you can then also just use `holochain -c <my-config>`.

That said, I don't want to oppose adding the `skip_hash_check` option.

Do you think hApp bundles as described would cater for all your needs, @pospi? Is there anything left to add to provide all needed information to setup a conductor for the multi-DNA scenarios you're dealing with?

**Comment by pospi** [comment]
Maybe.

> as long as the using hApps all reference the same version/hash of those dependencies, they should call into the same instance

Can I still run a test environment on a single machine with two independent agents viewing their own data within the same UIs, side by side in different browser windows?

Also wondering if `UIs.uri` can point to a path, so as to not have to run zipping in the build pipeline? Or to another local port to proxy through to? I think the likely setup is going to be external webpack dev servers connecting to exposed `interfaces` during development (this is what we are doing currently); webpack compiling output to a folder & then zipping contents for production deployment (is there an `hc` command for this? We need to start hashing, too- *UI is part of the protocol.*)

Another documentation request: where are the UI HTTP gateway(s) exposed? Different ports, or subpaths of a single UI server address? (ping @pdaoust)

**Comment by pdaoust** [comment]
@pospi are you referring to the RPC gateway that the UI talks to, or the gateway that serves up the UI itself? Gonna assume the former in my response: you can define different RPC interfaces (the intent is one per UI, I believe) and bind as many DNAs instances to them as you need. All DNA instances bound to an interface listen at the same URL: [you `POST` all your JSON-RPC calls to `/` and specify the DNA instance in the JSON-RPC body](https://developer.holochain.org/guide/latest/json_rpc_http.html).

This is, of course, assuming that you're using the `holochain` conductor which (until `hc` supports bundles) is the only thing that can run multiple DNAs and spin up multiple RPC interfaces.

**Comment by nmrshll** [comment]
Thanks for the fix !
