### ISSUE TITLE
review riker config

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#228]
currently we are using the default config that I found at https://github.com/riker-rs/riker/blob/master/config/riker.toml

considerations:

- i've symlinked this config into place to make it play nice with the rust compiler but this feels awkward
- riker has an open ticket to tweak how it handles config https://github.com/riker-rs/riker/issues/13
- i _think_ we can provide config in code rather than in toml which might be nicer as it would sit closer to the logic that uses it (this may also rely on the upstream ticket)
- is the default config right for us?

**Comment by leenozara** [comment]
Hi Holochain team,

Riker update: I've merged the update that eliminates the need for a configuration file `riker.toml` to be present. If it does not exist then default values will be used. You can remove the awkward symlink.

Riker and all related crates have been bumped up to `0.1.5`. You can update your dependencies:

```
[dependencies]
riker = "0.1.5"
riker-default = "0.1.5"
riker-patterns = "0.1.5"
```

@thedavidmeister has suggested a Riker Slack channel be set up. I'll look into this so that your team can easily get Riker support. Always happy to help.
