### ISSUE TITLE
Make wasm_utils it's own separate repo and crate

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-rust#264]
The reason I suggest this is for much faster and simpler builds of the hdk-rust , since its really only wanting to be dependent on that sub-crate

**Comment by ddd-mtl** [comment]
I tend to feel the same on this, but we also need wasm_utils in holochain-rust for some tests, and since I don't want holochain-rust to have dependency to hdk-rust, I left it there.
Maybe we should also move the tests in hdk-rust?
Also note that we aren't clear about keeping separate repos for holochain-rust, hdk-rust and app-spec-rust
