### ISSUE TITLE
document naming conventions

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#287]
because 👿 💥 🤔 

as i understand it:

- `Action` is `VerbNoun` e.g. `GetEntry`
- `ActionResponse` is `ActionName` e.g. `Action::GetEntry` results in `ActionResponse::GetEntry`
- reducer name is `reduce_action_name` e.g. `reduce_get_entry`
- Actor `Protocol` is `VerbNoun` or `Verb` e.g. `PutEntry` or `Setup`
- Result of a `Protocol` is `VerbNounResult` e.g. `PutEntryResult`
- method names that get something are the name of the thing being got, e.g. `entry()`
- method names that have side effect other than get are `verb_noun()` e.g. `put_entry()`
- avoid short names like `t`, `e`, `h` when `table`, `entry`, `header` would be clearer (almost always)

intent is to align with rust naming conventions https://doc.rust-lang.org/1.0.0/style/style/naming/README.html then fill in the gaps where our own code might be ambiguous

if in doubt refer to the rust conventions

if there is no clear fit then make something up, but make it "self documenting", i.e. explicit, descriptive and indicative of what it does/is/will happen

names should be as "boring" as possible

**Comment by ddd-mtl** [comment]
I agree with the first four points, but I think `PutEntry `should be `Put`.

Explanation:

## Our blind-spots
Blindspot in our thinking of naming conventions:
**API is language agnostic so we should not follow Rust conventions for naming the API**

and also:
**We have to differentiate end-user facing names from internal names.**

The most notable example is the dreaded `Entry`
We don't want the user to care about system and non-system entries, so we only use `entry` in the API.
But internally we have code that handles system entries and non-system entries differently, so we need names to differentiate them. **I propose `SysEntry` and `AppEntry`**. Internally we can still use `Entry` when we don't need that discernment.

Generally, **we must be clear which part of Holochain Rust code follows API naming from parts that follow internal naming**.

**I propose:**
- `ZomeApiFunctions` follows API naming, e.g. `LinkEntries`. (This leaks to `invoke_*()` functions.)
- `Actions `and `Protocol `follows internal naming, e.g. `AddLink`. (This leaks to reducers and ActionResponse.)

`invoke_*()` functions are where the transition is made, because this is where Actions are dispatched.

We will also need to have clear guidelines for global constants in the API.

## `entry()`

The Rust convention states not to use `get_*()` for accessors, which is fine, but it does also recommend using `get()` for container with keys/indexes, as stated [here](https://doc.rust-lang.org/1.0.0/style/style/naming/containers.html).

Our codebase is indeed confusing when `entry()` can be just an accessor, like in `pair.entry()` but also a load operation like in `table.entry()`.
This is why **I propose we use:**
- `entry()` for accessors
- `get()` for containers like HashTable
- `GetEntry()` for the API

<br/>

## Rust Convention blind-spots
The Rust Convention has blind-spots that I think we should address in our own way:
 - **global variables**: The convention doesn't specify anything for `static mut`. rustfmt seems to treat as global constants (`static`). But why not treat it as a local variable (`mut`) ? This is arbitrary rustfmt decision which is counter to the industry-wide convention of having constants be uppercase and variable be lowercase. To keep that convention **I propose we use `snake_case` for `static mut` variables**. I also recommend the `g_` prefix to indicate its a global variable, but this is more optional.
- **Enums for constants**: The convention doesn't differentiate Enum values that are constants from those that are variables. So Enums used as constants are currently `CamelCase` which is again counter to the industry-wide convention of having constants be uppercase and variable be lowercase.
This aberration is pretty obvious when you put side by side a constant Enum next to a bitflags, which is basically the same thing, but since bitflags are struct with consts its `SCREAMING_SNAKE_CASE`:

>     hdk::debug(&hdk::GetEntryMask::ENTRY_TYPE);
>     hdk::debug(&hdk::PkgRequest::EntryTypes);

So **I propose we use `SCREAMING_SNAKE_CASE` for constant Enums** in order to get coherence:
>     hdk::debug(&hdk::GetEntryMask::ENTRY_TYPE);
>     hdk::debug(&hdk::PkgRequest::ENTRY_TYPES);

rustfmt/clippy might not like this but we can deactivate it when appropriate.

**Comment by zippy** [comment]
I like this all very much, especially the distinction about API facing naming conventions vs internal Rust ones.

**Comment by sphinxc0re** [comment]
I disagree, we don't have a language agnostic API. We have mainly a Rust API. Every other language will be using the c-bindings. I also disagree with your notion of constants: Rust enums are enums, not constants. Constants are constants and should be used that way.

**Comment by thedavidmeister** [comment]
constants are commonly screaming snake case but this isn't industry wide

clojure: earmuffs like *my-const*
scala: PascalCase
lisp: +My-Const+
haskell: must start with lower case

also enum variants are not constants as @sphinxc0re pointed out, and rust uses PascalCase for enum variants

the screamingness of the constant naming convention seems more popular in languages/contexts where mutability is rampant and dangerous and less so where immutability is the de facto approach or handled more carefully at the language level

**Comment by thedavidmeister** [comment]
my thoughts on `Put` vs `PutEntry`:

- even if we make the argument that we want a language agnostic API, what is beneficial about dropping `Entry`? is the word `Entry` somehow coupled to Rust? would it cause problems in another language?
- `PutEntry` is clearer to me, i believe that some of the recent confusion/revelations re: pairs vs. headers. vs. entries was delayed and exacerbated due to "floating verbs"... when one person scans the code and sees `put()` or `Put`, do they necessarily look close enough at the type signatures to see what "thing" is being "put"? `
- i might even argue (haven't totally thought this through) that it is _because_ Rust offers a rich type system that we feel comfortable falling back to `Put` because you see `Put(Entry)` right there in the enum definition
  - can we rely on people always referring to the enum definitions when reviewing code elsewhere?
  - doesn't `Put` make the API less language agnostic than `PutEntry`?

thoughts on using raw `get()`

- if the concern is ambiguity between loading and access then i'd like to see an explicit convention around this, e.g. `fetch_entry` or `load_entry` or `lookup_entry`, not just `get`
  - rust seems to encourage naming things differently based on the expensiveness of the process, we could have `entry()` for access that is "free" and `get_entry()` for potentially expensive lookups
- the rust conventions say that `get` by itself should be used rarely and only when the thing being got is truly unambiguous, like getting the inner values of a wrapper/reference

`SysEntry` vs. `AppEntry`:

- i don't totally understand this, is this a naming convention or new types?
- can we mockup a simple example of what this looks like?
- does this extrapolate to things like `PutSysEntry` and `put_sys_entry()`?

**Comment by ddd-mtl** [comment]
By API, I mean end-user facing API. Like `hdk-rust/lib.rs`
All the code in `holochain-rust` is obviously Rust specific.

@thedavidmeister 
For `Put` vs `PutEntry`, my main point is to have 1:1 names between Actions/Protocols and actual methods that are called. In HashTable `put()` and `get()` seems okay since we are obviously putting and getting whatever item type the HashTable is storing, but I don't mind `PutEntry`.

I agree with having explicit convention based on the expensiveness of the process.

`SysEntry` and `AppEntry` are not types. It is for us to have better names when talking about them, and mentionning them in code. There is a bit of example code of that in the 188-linking PR. I have added `is_sys()` and `is_app()` methods to `Entry`.
Each SysEntry does have a type, as listed by the `enum EntryType`.
So we might not have a `put_sys_entry()` but probably have a `put_dna_entry()`.

**Comment by thedavidmeister** [comment]
@ddd-mtl ok awesome, i'll check out the `is_sys()` and `is_app()` as i work through the linking PR 👍 

i also agree that the rust naming conventions has limitations, which i pointed to in the mdbook doc in the PR for this issue... we're definitely going to have to keep chipping away at this

i think i'm missing something on the capitalisation thing, why can't we do

```rust
hdk::debug(&hdk::GetEntryMask::ENTRY_TYPE);
hdk::debug(&hdk::PkgRequest::EntryTypes);
```

are you referring to these, for example?

https://github.com/holochain/holochain-rust/blob/develop/core/src/hash_table/status/mod.rs#L11

i agree that is a bit confusing... maybe we can Pascal case the whole thing as `bitflags!` is a macro anyway and values for enum variants are not well supported in rust in general

**Comment by thedavidmeister** [comment]
@ddd-mtl i reckon i'll try out something like `store()` and `retrieve()` for CAS and really strip the API back to what is generic, so then high level things can focus on what is specific to their needs, e.g. headers for chains and entries for the DHT

**Comment by ddd-mtl** [comment]
@thedavidmeister 
Yes, we could also use EnumFlags instead of BitFlags, and have it be CamelCase.
But I read `GetEntryMask::EntryType` as a type, not as a value, whereas I read `GetEntryMask::ENTRY_TYPE` as a (const) value. Like the Rust convention states:
> CamelCase for "type-level" constructs (types and traits) and snake_case for "value-level" constructs

So `hdk::debug(&hdk::GetEntryMask::EntryType)` is in itself a bit confusing to me.

When using C-style enums `GetEntryMask::EntryType` is 'value-level' not 'type-level', so should follow 'value-level' naming convention...

**Comment by thedavidmeister** [comment]
hurrr, it's a value that represents a type... not a rust type in the compiler, but an entry "type"

there's also the `GetEntryMask::entry_type` option that would be a snake_case value level construct

it's subtle :/ i was hoping for something that is stupid obvious to minimise the chance of future renaming/merge conflicts/noise

**Comment by ddd-mtl** [comment]
Your PascalCase PR, reminded me that Rust Convention has mistaken camelCase with PascalCase...
