### ISSUE TITLE
decide and implement a system for support/deprecation of new/old rust versions

### ISSUE THREAD

**Issue by sphinxc0re** [holochain/holochain-rust#48]
child of #117 

As the README says, we are currently targetting Rust 1.26.2, which is very specific. I think we should be able to always target the current stable version of Rust since it is developed in a backwards compatible manner.

**Comment by thedavidmeister** [comment]
@sphinxc0re thanks for opening this, there are a lot of opinions/discussion floating around here and it's good to have a place to summarise where things are at:

- as of today this was set to `nightly-2018-06-01` as some clippy failures from the other day were breaking travis builds, but i suppose i forgot the README, sorry!
- from what i've seen, the stable version of rust is missing things we want:
  - WASM support/tooling being developed on top of by @lucksus 
  - clippy/linting tools are tracking nightly and don't seem to work well against stable
- "backwards compatible" isn't all we might want, is it really OK to go to the length of hashing DNA/zome code so that even adding a comment "forks" a DHT/network, but then allow the rust version/dependencies of hc_core itself to change multiple times per month without being pinned/reviewed?
- for the future, we've discussed using something like nix to not just pin a few versions here and there, but allow/enforce fully deterministic builds for the whole hc stack, so that rust dependencies would have integrity checks analogous to zome integrity checks
- if we want to support multiple versions and environments, we can relatively easily enumerate the versions we support so that we can throw them at travis
- nightly versions of rust come out so fast and libraries tracking nightly lag enough that i saw travis breaking almost every morning last week, which hurt our productivity while the team had a lot of balls in the air, and it led to tests being temporarily turned off or ignored on travis twice, which is bad
- stable versions of rust come out infrequently enough that it's not hard to imagine us implementing a process where we bump and deprecate versions manually as they come and go
- we can definitely test against both stable and nightly on travis using the `allow_failures` flag on travis, so then at least we know ahead of time what we're up against :)
  - in some sense, we'd then be "targetting" both stable and nightly, but with the understanding that failures in a new version don't "stop the line" until we decide we're ready to bump officially supported versions

**Comment by sphinxc0re** [comment]
My reasoning here is that the whole project doesn't need to use nightly builds. We are perfectly able to build and agent binary on stable Rust. The code that actually has to compile to Wasm could use nightly as a separate build path.

**Comment by jamesray1** [comment]
[M4-core] P5-sometimesoon m0-build

**Comment by thedavidmeister** [comment]
@jamesray1 wow, this has progressed a lot since then

currently the only way to track rust properly across all repos and zomes is through holonix as an upstream

rust versions are pinned to holonix versions and holonix versions are pinned to all rust code written

https://docs.holochain.love/docs/rust/

https://hackmd.io/ShgxFyDVR52gnqK7oQsuiQ

we can't yet target `stable` but the number of reasons for this are steadily decreasing (e.g. async/await just recently landed in stable)

**Comment by jamesray1** [comment]
Right yeah sorry I should've acknowledged those points as I was aware of them. I had a quick look at the hackmd article, however currently I need to stop voluntary efforts to focus on looking for a job.
