### ISSUE TITLE
review whether it is necessary to clone pairs in source chain push()

### ISSUE THREAD

**Issue by thedavidmeister** [holochain/holochain-rust#52]
flagged in #51 

the pair is cloned for both validation and the final insert, perhaps this can be done more efficiently without the cloning...

**Comment by murrayjbrown** [comment]
@thedavidmeister  I've been looking into this and found that the code has been refactored considerably since this issue was raised, with relevant changes just in the past couple of days.

The chain pair cloning is potentially quite expensive, depending on the size of the entry content. Consequently, I'm submitting a pull request with the `hash_table::entry::Entry` structure and related referencing code refactored to use a Box smart pointer for immutable content so that entry cloning will be more efficient for large content strings.

**Comment by thedavidmeister** [comment]
@murrayjbrown thanks, more changes coming soon around this!

the overhead might get worse when we implement bundles as that will likely involve speculative validation/writes and rollbacks, so avoiding clones there would be good

@zippy fyi

**Comment by zippy** [comment]
Pretty sure this is way out-of-date now...

**Comment by thedavidmeister** [comment]
yes and i think we'd benchmark a change like this nowadays :)
