### ISSUE TITLE
trying to compile holochain-rust

### ISSUE THREAD

**Issue by vsraptor** [holochain/holochain-rust#583]
Any idea of why I'm getting errors when trying to compile : 
```
   Checking riker-default v0.1.8                                                                                                                                                             
    Checking failure v0.1.3                                                                                                                                                                   
    Checking holochain_net v0.0.1 (file:///my/compile/holochain/net)                                                                                                                          
    Checking holochain_core_types v0.0.1 (file:///my/compile/holochain/core_types)                                                                                                            
    Checking holochain_net_ipc v0.1.0 (file:///my/compile/holochain/net_ipc)                                                                                                                  
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)n_core_types, holochain_net_ipc                                                                       
  --> core_types/src/error/error.rs:68:12
   |
68 |         Ok(serde_json::to_string(self)?)
   |            ^^^^^^^^^^
   |
   = help: add #![feature(extern_prelude)] to the crate attributes to enable

warning: returning the result of a let binding from a block. Consider returning the expression directly.                                                                                      
  --> core_types/src/entry_type.rs:95:9
   |
95 |         ret
   |         ^^^
   |
   = note: #[warn(let_and_return)] on by default
note: this expression can be directly returned
  --> core_types/src/entry_type.rs:83:19
   |
83 |           let ret = match *self {
   |  ___________________^
84 | |             EntryType::App(ref s) => s,
85 | |             EntryType::AgentId => sys_prefix!("agent_id"),
86 | |             EntryType::Deletion => sys_prefix!("deletion"),
...  |
93 | |             EntryType::AgentState => sys_prefix!("agent_state"),
94 | |         };
   | |_________^
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#let_and_return

warning: module has the same name as its containing module
 --> core_types/src/error/mod.rs:2:1
  |
2 | mod error;
  | ^^^^^^^^^^
  |
  = note: #[warn(module_inception)] on by default
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#module_inception

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `holochain_core_types`.                                                                                                                                              

To learn more, run the command again with --verbose.
make: *** [clippy] Error 101

```

```
$ rustc --explain E0658
An unstable feature was used.

Erroneous code example:
```
```rust
#[repr(u128)] // error: use of unstable library feature 'repr128'
enum Foo {
    Bar(u64),
}
```
```

If you're using a stable or a beta version of rustc, you won't be able to use
any unstable features. In order to do so, please switch to a nightly version of
rustc (by using rustup).

If you're using a nightly version of rustc, just add the corresponding feature
to be able to use it:

```
```rust
#![feature(repr128)]

#[repr(u128)] // ok!
enum Foo {
    Bar(u64),
}
```

**Comment by sphinxc0re** [comment]
I updated the formatting of your description for clarity. Could you elaborate on what you did to compile holochain?

**Comment by fonzarely** [comment]
@vsraptor I had the same issue so switched to master branch and it compiled fine.

@sphinxc0re I'm using the homebrew rustup package. develop branch does not compile on mac.
I did check the travis file and saw it use a windows image for the CI. It may partly explain why it works on the CI but not on mac. Regards

**Comment by sphinxc0re** [comment]
Did you run `make`?

**Comment by fonzarely** [comment]
Yes I did, also used make clean after the fail on develop branch.

**Comment by rednaxus** [comment]
hi...i'm also failing to compile on Mac...using the standard rustup


    Checking riker-patterns v0.1.8                                                                                                                                           
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)holochain_core_types, riker-mapvec, riker-patterns                                   
   --> core_types/src/error/error.rs:169:11
    |
169 | impl From<base64::DecodeError> for HolochainError {
    |           ^^^^^^
    |
    = help: add #![feature(extern_prelude)] to the crate attributes to enable

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> core_types/src/error/error.rs:170:20
    |
170 |     fn from(error: base64::DecodeError) -> Self {
    |                    ^^^^^^
    |
    = help: add #![feature(extern_prelude)] to the crate attributes to enable

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> core_types/src/error/error.rs:175:11
    |
175 | impl From<reed_solomon::DecoderError> for HolochainError {
    |           ^^^^^^^^^^^^
    |
    = help: add #![feature(extern_prelude)] to the crate attributes to enable

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
   --> core_types/src/error/error.rs:176:20
    |
176 |     fn from(error: reed_solomon::DecoderError) -> Self {
    |                    ^^^^^^^^^^^^
    |
    = help: add #![feature(extern_prelude)] to the crate attributes to enable

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> core_types/src/agent.rs:28:17
   |
28 |         let s = base64::decode(&s)?;
   |                 ^^^^^^
   |
   = help: add #![feature(extern_prelude)] to the crate attributes to enable

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> core_types/src/agent.rs:43:9
   |
43 |         base64::encode(&enc[..]).replace("+", "-").replace("/", "_")
   |         ^^^^^^
   |
   = help: add #![feature(extern_prelude)] to the crate attributes to enable

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> core_types/src/agent.rs:79:19
   |
79 |         let buf = base64::decode(&buf)
   |                   ^^^^^^
   |
   = help: add #![feature(extern_prelude)] to the crate attributes to enable

error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
  --> core_types/src/agent.rs:95:19
   |
95 |         let key = base64::decode(&self.key).expect("corrupt identity key");
   |                   ^^^^^^
   |
   = help: add #![feature(extern_prelude)] to the crate attributes to enable

    Checking parking_lot v0.6.4                                                                                                                                              
    Checking riker-default v0.1.8                                                                                                                                            
error: module has the same name as its containing module=======>     ] 220/241: semver, holochain_core_types, parking_lot, riker-default                                     
 --> core_types/src/error/mod.rs:2:1
  |
2 | pub mod error;
  | ^^^^^^^^^^^^^^
  |
  = note: `-D module-inception` implied by `-D warnings`
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#module_inception

    Checking crossbeam-channel v0.2.6                                                                                                                                        
    Checking ignore v0.4.4                                                                                                                                                   
error: aborting due to 9 previous errors=======================>     ] 223/241: semver, holochain_core_types, ignore                                                         

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `holochain_core_types`.                                                                                                                             
warning: build failed, waiting for other jobs to finish...
error: build failed                                                                                                                                                          
make: *** [clippy] Error 101

**Comment by willemolding** [comment]
Do any of these build errors still exist for anyone?
