### ISSUE TITLE
core_types struct for building json for `P2pConfig`

### ISSUE THREAD

**Issue by maackle** [holochain/holochain-rust#841]
This is *not* the idea proposed in #637 or #816 to use structs for P2pConfig. The idea here is to have an enum which contains only the information about network config that core crates need to know about. This enum can go `.into()` a `P2pConfig` where all the other config data will be fleshed out. This was discussed a little here: https://github.com/holochain/holochain-rust/pull/835#issuecomment-452591376

We could hijack `NetworkConfig` for this, or create a new enum altogether.

**Comment by thedavidmeister** [comment]
yes, a big :+1: from me

while i don't agree with the reasons for needing this in the first place, it seems like a very good compromise to me

we can track our interop with the networking crates from core without changing the way networking is modified

we don't put structs in the networking code being iterated currently, so no merge/architecture conflicts there

if the config spec evolves, we can use the compiler to keep across it rather than manually auditing strings across the codebase

we can stop using `json!` outside networking, which has several limitations outlined in the mdbook

it will also help in context of changes like #810 that seek to improve our success rate of actually putting valid JSON inside JsonString - which causes subtle and hard to reach bugs when not done

**Comment by maackle** [comment]
> i don't agree with the reasons for needing this in the first place

@thedavidmeister what would you say are the reasons?

**Comment by thedavidmeister** [comment]
@maackle this issue is about a constructive immediate solution to help core/networking interface smoothly

i don't want to derail that with a rambling back story (you linked to relevant PRs anyway)

**Comment by neonphog** [comment]
I may or may not be understanding what is proposed here. Let me frame it from my perspective and you guys can tell me if I got it.

I also do not want `json!` to be used anywhere in rust, not even the networking modules.

We have need to pass opaque configuration blobs around in multiple places... json is the most inter-operable encoding for these blobs. We have need for these blobs to be specified in end-user editable configuration files. I'm not sure toml is the best place for putting json : /

Rust CORE needs to know:

- NetworkKind - (MOCK, IPC, etc)
- NetworkSpawnConfig - OPAQUE - for IPC, this is n3h_dir, n3h_mode, etc, but core doesn't need to parse these!
- NetworkReconnectConfig - OPAQUE - for IPC, if a different container did the spawn, this could contain the ipcUri that was returned, but again, if the spawn action returned an OPAQUE json blob, CORE would not need to parse it!

Rust net_ipc needs to know (for the Spawn case):

- spawn environment things n3h_dir, env vars etc...
- n3h config - OPAQUE - the config that n3h itself needs to run, p2p interface binding directives, etc - but net_ipc does not need to parse these!

so, from my *ideal* perspective some config somewhere would look like:

```json
{
  backend: 'ipc',
  spawn: {
    dir: '~/n3h',
    env: {
      N3H_MODE: 'HACK'
    }
    config: {
      p2p_bind: 'ip4/0.0.0.0/tcp/0'
    }
  }
}
```

alas, rust will parse everything here... core would need to re-stringify the spawn section... then net_ipc would parse the spawn section, pull out dir, env and need to re-stringify the config section... horrible PITA

anyone have thoughts to make this better?

**Comment by maackle** [comment]
Yeah I didn't do a very good job of gathering the key points into this issue, everything is spread out across a few conversations in other PRs (linked in the description).

My idea is that the config @neonphog mentioned should deserialize into an intermediate enum that core can use. BTW the following should also be valid config, suggesting it's a an enum [internally tagged](https://serde.rs/enum-representations.html#internally-tagged) by "backend"

```
{
  "backend": "mock",
  "networkName": "foo",
}
```

This intermediate config contains just the info core needs to do its thing. This enum should also have an `impl Into<P2pConfig>` because another thing core needs to do is have a fully valid `P2pConfig` to pass into various functions.

I think this would be useful even if P2pConfig were backed by an enum itself. It restricts core from mucking with config it doesn't need to know about, but gives it access to the config it does need to know about. (I would have used this yesterday when I was considering using regex to extract the networkName from a raw mock config).

**Comment by neonphog** [comment]
Cool, if I'm understanding correctly, this enum sounds like a good step. We can tackle removing some of the other parsing that is currently happening as a separate effort?

@ddd-mtl thoughts?

**Comment by ddd-mtl** [comment]
P2pConfig is already "backed" by an enum which is NetworkKind.
After fixing some things in the MockWorker, now InMemoryWorker, it seems Michael was not making use of that enum and was struggling with a full json-string of the P2pConfig instead of using the struct with the enum.

**Comment by ddd-mtl** [comment]
Yes, I meant `P2pBackendKind`. I don't know what happened to me last night that made me say NetworkKind...
The purpose of `P2pConfig` is to provide a code facade around the raw json for configuring the network so that people don't have to deal with the raw json.
So if you have to deal with a serdeValue, than it means you are using P2pConfig wrong or that P2pConfig is not achieving its goal and needs an improvement.

If you want a network config for the InMemoryWorker, you can use:
```rust
P2pConfig::new_with_unique_memory_backend()
P2pConfig::new_with_memory_backend(server_name: &str)
```

If you want a network config for the IpcWorker, you can use:
```rust
P2pConfig::default_ipc_spawn()
P2pConfig::default_ipc_uri(maybe_ipc_binding: Option<&str>) 
```

If you want to provide your own custom config, than the idea is to write it in a json file and give that filepath as input with `P2pConfig::from_file(filepath: &str)`.

The API does not provide a way to modify a config in code as for now there is no reason to do so.

Hope that clears up things for you.

**Comment by maackle** [comment]
@ddd-mtl yes those functions are a step in the right direction. I didn't know about those when I working on whatever I was working on. I saw some other code creating a JSON string from scratch, so I did the same (I think [here](https://github.com/holochain/holochain-rust/blob/dc2b8b29de633321fb7f823d42ad317b213bd756/container_api/src/container/base.rs#L288))

The only thing that's missing here is the notion of "selective opacity". As @neonphog mentioned most of the P2pConfig should be totally opaque to core, which I'm on board with. However by using something like `P2pConfig::new_with_memory_backend` we go straight from a value we care about into a totally opaque config, and we can't easily get that value back out. In `Container`, we actually need to store the `P2pConfig` that will be used to create each new instance. 

For instance when creating an InMemory config, the only thing core cares about is the network name. If I create a P2pConfig immediately from that network name, I lose access to the network name (I have to parse JSON if I want to get it out). So then I'd have to store that name separately if I wanted to have access to it. Same goes for IPC URI, once a value goes into a P2pConfig it's hard to get back out.

I recognize I'm already spending more time explaining it than it would take to write it at this point, but I'm going to keep on. The idea is a simple struct like this:

```rust
enum P2pConfigBuilder {
    InMemory(network_name: String),
    FromFile(file_path: PathBuf),
    Ipc(ipc_uri: String),
}

impl From<P2pConfigBuilder> for P2pConfig {
    // you get the idea...
    // .into() would get called when it's time to "lock it in" and get a fully opaque struct to pass on to net
}
```

That's pretty much it. From that you can build a full `P2pConfig`, but it's an object that lets core still have access to the values it might need to access later.

This came up because at one point I wanted to access the network name of the config that I created and stored, but gave up because I didn't want to either (A) parse a json string or (B) store a redundant Optional copy of the network name (because the network is not necessarily in memory) just so I can print it out later.

**Comment by ddd-mtl** [comment]
I see what you mean and it makes sense to me.
This is however a different concern from your previous one I was responding to, which is: "we have to also construct a raw serde_json::Value, which is the problem I want to avoid"
The use case I see you talk about here now is the ability to reuse the same inputs you used to create a P2pConfig and the ability to easily identify the config used with some handle.
It doesn't make sense for P2pConfig to provide a way to get a value back from the config since you are providing those values in the first place, so your proposed solution seems fine to me.

**Comment by ddd-mtl** [comment]
Oh and you can actually get the network_name back by calling `P2pNetwork::endpoint()`
It will gave back the uri in the IPC case.

**Comment by maackle** [comment]
@ddd-mtl yes I neglected to mention that part of the use case this time. I'm glad you see the usefulness too. Next time we have to work with `P2pConfig` I will probably write this small enum and refactor existing core code, or someone else can feel free to do the same.

**Comment by maackle** [comment]
It's been a long time since this conversation happened, seems stale, closing
