### ISSUE TITLE
validate()

### ISSUE THREAD

**Issue by zippy** [holochain/holochain-rust#97]
child of #89
child of #88

**Comment by thedavidmeister** [comment]
- there should be an enum for not implemented
- reference genesis for example on how to implement
- split out each hook into a file
- figure out what it should be called (not hook, but similar to hook)

**Comment by thedavidmeister** [comment]
- dispatch the validate action from inside the commit action
- failing validation might need to be handled differently for local vs. incoming from DHT
  - you should test your own data before committing and sending it
  - you should keep invalid data coming in so that you can defend against malicious actors

**Comment by thedavidmeister** [comment]
- validate put vs. validate commit covers local vs. incoming
  - commit is only on authoring
  - put is both authoring and DHT receiving
  - for local it must be valid commit AND valid put
  - for receiving it must only be a valid put
- validate can chain sensor off of commit
  - check this doesn't end up in an infinite loop
